<!DOCTYPE html>  
<html lang="fr">  
    <head>  
        <meta charset="utf-8" />  
        <meta name="viewport" content="width=device-width, initial-scale=1" />  
        <title>Boutique Kebab</title>  
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"  
              rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"  
              crossorigin="anonymous">  
    </head>  
    <body>  
        <header>  
            <nav class="navbar navbar-expand-lg bg-light px-3">  
                <h1 class="d-none">Boutique de Kebabs</h1>  
                <a class="navbar-brand" href="/res03-projet-final/">Boutique kebabs</a>  
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">  
                    <li class="nav-item">  
                        <a class="nav-link" href="/res03-projet-final/">Accueil</a>  
                    </li>  
                    <li class="nav-item">  
                        <a class="nav-link" href="/res03-projet-final/produits">Liste des produits</a>  
                    </li>  
                    <li class="nav-item dropdown">  
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">  
                            Catégories  
                        </a>  
                        <ul class="dropdown-menu">  
                            <li><a class="dropdown-item" href="/res03-projet-final/categories/action">Normal</a></li>  
                            <li><a class="dropdown-item" href="/res03-projet-final/categories/heroic-fantasy">Heroic-Fantasy</a></li>  
                            <li><a class="dropdown-item" href="/res03-projet-final/categories/science-fiction">Science-Fiction</a></li>  
                        </ul>  
                    </li>  
                    <li class="nav-item">  
                        <a class="nav-link" href="/res03-projet-final/creer-un-compte">Inscription</a>  
                    </li>  
                    <li class="nav-item">  
                        <a class="nav-link" href="/res03-projet-final/connexion">Connexion</a>  
                    </li>  
                </ul>  
            </nav>  
        </header>  
        <?php require "templates/{$page}.phtml"; ?>  
        <footer>  
  
        </footer>  
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"  
                integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"  
                crossorigin="anonymous">  
        </script>  
    </body>  
</html>