<main class="container py-5">  
    <h2 class="mb-5">Créer un compte</h2>  
    <form method="post" action="/res03-projet-final/check-creer-un-compte" class="col-4">  
        <input type="hidden" name="formName" id="formName" value="registerForm" />  
        <fieldset class="mb-3">  
            <label for="username" class="form-label">  
                Nom d'utilisateur  
            </label>  
            <input type="text" name="username" id="username" class="form-control" required />  
        </fieldset>  
        <fieldset class="mb-3">  
            <label for="email" class="form-label">  
                Email  
            </label>  
            <input type="email" name="email" id="email" class="form-control" required />  
        </fieldset>  
        <fieldset class="mb-5">  
            <label for="password" class="form-label">  
                Mot de passe 
            </label>  
            <input type="password" name="password" id="password" class="form-control" required />  
        </fieldset>  
        <button type="submit" class="btn btn-primary">Créer un compte</button>  
    </form>  
</main>