

<main>  
    <h1>Voici la liste des produits</h1>  
</main>

<main class="container py-5">  
    <h2 class="mb-5">La liste des films</h2>  
    <section class="row">
        <?php 
        foreach($data['products'] as $product)
        { 
        
        ?>
            
        <article class="card col-3 mx-2 p-5">  
            <header>  
                <h3 class="card-title"><?= $product->getName(); ?></h3>  
            </header>  
            <p class="card-text">  
                <?= $product->getDescription(); ?>  
            </p>  
            <footer>  
                <a href="/res03-projet-final/produits/<?= $product->getSlug() ?>" class="btn btn-success"><?= $product->getName() ?></a>  
            </footer>  
        </article>
        <?php } ?>
    </section>  
</main>